/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bridgeTokenSol from "./BridgeToken.sol";
export type { bridgeTokenSol };
import type * as interface from "./interface";
export type { interface };
export type { BridgeProxy } from "./BridgeProxy";
export type { ChainBridge } from "./ChainBridge";
