/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bridgeTokenSol from "./BridgeToken.sol";
export * as interface from "./interface";
export { BridgeProxy__factory } from "./BridgeProxy__factory";
export { ChainBridge__factory } from "./ChainBridge__factory";
